### ISSUE TITLE
Setup script fails due to `id` balance 0 

### ISSUE THREAD

**Issue by 0xNilsOlav** [paul-schaaf/solana-escrow#6]
Currently the setup script is failing with the following log output:
```
Requesting SOL for Alice...
Requesting SOL for Bob...
Creating Mint X...
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
```

Script runs successfully after airdropping sol to the `id` public key address, so think the fix is to add another `requestAirdrop` to that address before creating the mint.

**Comment by 0xNilsOlav** [comment]
Ah, that makes sense - I started the validator manually and then ran `npm run all` as instructed in the [scripts README](https://github.com/paul-schaaf/solana-escrow/tree/master/scripts). 

I'm on an M1 mac and needed to build from source with the 1.7 branch because of that, so needed to run `solana-test-validator` from that directory rather than the system one installed to `.local/share/solana/install`. That's a me problem, but IMO it would be cleaner to have the start-validator script just start the validator rather than also doing some initialization.

**Comment by 0xNilsOlav** [comment]
Some background on how I got to this point:

I started by trying to use the UI in the guide (which is why I had started the test validator manually) and thought I had everything set up correctly, but got the error below and didn't know what to do with that so thought I'd try the script instead.

```
failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x4
```
(the guide is awesome, btw - really great introduction to programming on Solana!)

**Comment by paul-schaaf** [comment]
@0xNilsOlav I merged your PR but I'm still gonna keep the initialization in the script as well. If you dont want initialization, you can just use the `solana start-validator` command after all. That said, I'll rename it to `setup-validator` to make it more distinct.

Have you managed to find the cause of the error with the help of the scripts?

**Comment by weihwork** [comment]
I have the same problem with my mac m1,  because there is something wrong with solana-test-validator, so i use devnet. 

I use 'solana airdrop instruction' get sol for id, alice and bob first, and use 'solana program deploy' instruction load solana_escrow.so program. Because of escrow program id changed, so replace keys/program_pub.json with the pubkey of deploy/solana_escrow-keypair.json.

Finally, change setup.ts,alice.ts,bob.ts connection with https://api.devnet.solana.com,  delete setup.js requestAirdrop instruction. 

npm run setup  -->  npm run alice  -->  npm run bob.

**Comment by weihwork** [comment]
I have the same problem with my mac m1, because there is something wrong with solana-test-validator, so i use devnet.

I use 'solana airdrop instruction' get sol for id, alice and bob first, and use 'solana program deploy' instruction load solana_escrow.so program. Because of escrow program id changed, so replace keys/program_pub.json with the pubkey of deploy/solana_escrow-keypair.json.

Finally, change setup.ts,alice.ts,bob.ts connection with https://api.devnet.solana.com, delete setup.ts requestAirdrop instruction.

npm run setup --> npm run alice --> npm run bob.
